### PR TITLE
CHS Translation

### PR DESCRIPTION
**Pull request by WuzgXY-GitHub**

### CODE REVIEW

**Review by quek04 — CHANGES_REQUESTED** [review]
manually written files do not belong in src/generated

**Comment by WuzgXY-GitHub** [comment]
So should I put the file into `src/main/resources/assets/undergarden/lang`?

By the way, the translation is reviewed and approved by some other translators丨[The PR](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package/pull/937)

**Comment by quek04** [comment]
yeah, putting it there should work

**Comment by WuzgXY-GitHub** [comment]
It should be OK now

**Comment by quek04** [comment]
could we get this up to date with the current version? you made a translation during a period of time where I was changing a lot of things so some things might be outdated now

**Comment by WuzgXY-GitHub** [comment]
> could we get this up to date with the current version? you made a translation during a period of time where I was changing a lot of things so some things might be outdated now 

Of course. I will finish this ASAP

**Review by quek04 — APPROVED** [review]

**Pull request closed without merging**
