### PR TITLE
Properly Tag Music Discs

### PR DESCRIPTION
**Pull request by masonalph**
Adds appropriate music disc tag to relevant items.

Making the PR again because I'm bad at github and removed the original

### CODE REVIEW

**Comment by GizmoTheMoonPig** [comment]
This is not the way to add tags. 
As this project uses datagen, you need to add a line of code to https://github.com/quek04/undergarden/blob/1.21/src/main/java/quek/undergarden/data/UGItemTags.java and run the runData task in gradle. Otherwise this file will be removed the next time someone runs that task

**Comment by masonalph** [comment]
Thank you for taking the time to explain the issue @GizmoTheMoonPig. Taking another pass at this shortly.

**Comment by masonalph** [comment]
@GizmoTheMoonPig 
For review, ignore my clusterfuck of branch management and just look at the diff for both of our sakes.

**Comment by GizmoTheMoonPig** [comment]
looks good, thanks for doing this :)

**Pull request merged**
