### PR TITLE
Added material specific tags

### PR DESCRIPTION
**Pull request by NielsPilgaard**
Added material specific tags to nuggets, ingots, ores and storage_blocks, completes #52
This should, among other things, allow JAOPCA to generate dusts and other processing materials for Undergarden metals.

### CODE REVIEW

**Comment by quek04** [comment]
oh cool, thank you

**Comment by quek04** [comment]
did you use the datagen?

**Comment by NielsPilgaard** [comment]
I did not, I just placed it in that folder since the rest was there too :)

**Comment by quek04** [comment]
i think that will cause issues

**Comment by quek04** [comment]
the files in generated need to be generated with code, not manually added

**Comment by NielsPilgaard** [comment]
Ah alright, my bad, I'll get that fixed :)

**Comment by NielsPilgaard** [comment]
There we go, I hope that's better.

**Comment by quek04** [comment]
thanks! all looks good now

**Pull request merged**
